In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/cars_data_post_model_selection.csv')

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3,petrol,20979,manual,fwd,hatchback,5,1199,84.88,5
1,agra,745000,maruti suzuki,baleno,4,petrol,20176,manual,fwd,hatchback,5,1197,81.86,3
2,agra,465000,hyundai,grand i10,3,cng,41448,manual,fwd,hatchback,5,1197,81.86,7
3,agra,546000,maruti suzuki,celerio,3,petrol,8527,manual,fwd,hatchback,5,998,67.04,3
4,agra,428000,hyundai,santro,4,cng,102049,manual,fwd,hatchback,5,1086,68.05,5

In [ ]:
df.isnull().sum()

region           0
price            0
manufacturer     0
model            0
cylinders        0
fuel             0
odometer         0
transmission     0
drive            0
type            69
seats            0
engine_cc        0
max_power        0
age              0
dtype: int64

In [ ]:
sorted(df['manufacturer'].unique().tolist())

['audi',
 'bmw',
 'chevrolet',
 'citroen',
 'datsun',
 'fiat',
 'force',
 'ford',
 'honda',
 'hyundai',
 'isuzu',
 'jaguar',
 'jeep',
 'kia',
 'land rover',
 'lexus',
 'mahindra',
 'mahindra renault',
 'maruti suzuki',
 'mercedes-benz',
 'mg',
 'mini',
 'mitsubishi',
 'nissan',
 'others',
 'porsche',
 'renault',
 'skoda',
 'tata',
 'toyota',
 'volkswagen',
 'volvo']

In [ ]:
df.groupby('manufacturer')

In [ ]:
manufacturer = df['manufacturer'].unique().tolist()

In [ ]:
manufacturer

['tata',
 'maruti suzuki',
 'hyundai',
 'toyota',
 'honda',
 'mahindra',
 'mg',
 'ford',
 'nissan',
 'volkswagen',
 'audi',
 'kia',
 'datsun',
 'skoda',
 'renault',
 'mercedes-benz',
 'chevrolet',
 'bmw',
 'jeep',
 'jaguar',
 'mini',
 'volvo',
 'citroen',
 'land rover',
 'isuzu',
 'porsche',
 'lexus',
 'others',
 'bentley',
 'force',
 'fiat',
 'mitsubishi',
 'mahindra renault']

In [ ]:
f_df = df[df['manufacturer'] == 'manufacturer']

In [ ]:
f_df.head()

Empty DataFrame
Columns: [region, price, manufacturer, model, cylinders, fuel, odometer, transmission, drive, type, seats, engine_cc, max_power, age]
Index: []

In [ ]:
df['manufacturer_clean'] = df['manufacturer'].str.strip().str.lower()

manufacturer = sorted(df['manufacturer_clean'].dropna().unique().tolist())
filtered_df = df[df['manufacturer_clean'].isin(manufacturer)]

In [ ]:
filtered_df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age,manufacturer_clean
0,agra,1.811562,tata,tiago,3,petrol,20979,manual,fwd,hatchback,5,1199,84.88,5,tata
1,agra,2.134166,maruti suzuki,baleno,4,petrol,20176,manual,fwd,hatchback,5,1197,81.86,3,maruti suzuki
2,agra,1.731656,hyundai,grand i10,3,cng,41448,manual,fwd,hatchback,5,1197,81.86,7,hyundai
3,agra,1.865629,maruti suzuki,celerio,3,petrol,8527,manual,fwd,hatchback,5,998,67.04,3,maruti suzuki
4,agra,1.663926,hyundai,santro,4,cng,102049,manual,fwd,hatchback,5,1086,68.05,5,hyundai

In [ ]:
# df['manufacturer_clean'] = df['manufacturer'].str.strip().str.lower()

manufacturer = sorted(df['manufacturer'].unique().tolist())
filtered_df = df[df['manufacturer'].isin(manufacturer)]

In [ ]:
filtered_df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,1.811562,tata,tiago,3,petrol,20979,manual,fwd,hatchback,5,1199,84.88,5
1,agra,2.134166,maruti suzuki,baleno,4,petrol,20176,manual,fwd,hatchback,5,1197,81.86,3
2,agra,1.731656,hyundai,grand i10,3,cng,41448,manual,fwd,hatchback,5,1197,81.86,7
3,agra,1.865629,maruti suzuki,celerio,3,petrol,8527,manual,fwd,hatchback,5,998,67.04,3
4,agra,1.663926,hyundai,santro,4,cng,102049,manual,fwd,hatchback,5,1086,68.05,5

In [ ]:
df['type'].value_counts()

type
hatchback        24098
sedan            16223
suv              14728
muv               2993
minivans           529
crossover          161
pickup trucks       53
convertibles        28
coupe               20
wagon                8
hybrids              4
Name: count, dtype: int64

In [ ]:
df['type'].isnull().sum()

np.int64(69)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58914 entries, 0 to 58913
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   region              58914 non-null  object
 1   price               58914 non-null  float64
 2   manufacturer        58914 non-null  object
 3   model               58914 non-null  object
 4   cylinders           58914 non-null  int64
 5   fuel                58914 non-null  object
 6   odometer            58914 non-null  int64
 7   transmission        58914 non-null  object
 8   drive               58914 non-null  object
 9   type                58845 non-null  object
 10  seats               58914 non-null  int64
 11  engine_cc           58914 non-null  int64
 12  max_power           58914 non-null  float64
 13  age                 58914 non-null  int64
 14  manufacturer_clean  58914 non-null  object
dtypes: float64(2), int64(5), object(8)
memory usage: 6.7+ MB

In [ ]:
df.isnull().sum()

region                 0
price                  0
manufacturer           0
model                  0
cylinders              0
fuel                   0
odometer               0
transmission           0
drive                  0
type                  69
seats                  0
engine_cc              0
max_power              0
age                    0
manufacturer_clean     0
dtype: int64

In [ ]:
df[df['type'].isnull()]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
23681,pune,550000,bmw,3 series,4,diesel,58987,automatic,rwd,NaN,5,1995,170.00,16
23682,new delhi,149000,mercedes-benz,s-class,6,diesel,5500,automatic,awd,NaN,5,2925,281.61,3
23683,new delhi,1050000,volvo,s60,4,diesel,89632,automatic,fwd,NaN,5,1984,181.00,13
23686,mumbai,3800000,volvo,xc90,4,diesel,64000,automatic,awd,NaN,7,1969,235.00,11
23687,chandigarh,650000,bmw,3 series,4,diesel,70000,automatic,rwd,NaN,5,1995,170.00,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23744,bangalore,1395000,volvo,s60,4,diesel,78000,automatic,fwd,NaN,5,1984,181.00,12
23745,chennai,1050000,volvo,s 80,5,diesel,125011,automatic,fwd,NaN,5,1984,163.00,14
23746,bangalore,500000,bmw,3 series,4,diesel,67276,automatic,rwd,NaN,5,1995,170.00,16
28473,new delhi,160000,mercedes-benz,s-class,6,diesel,5000,automatic,awd,NaN,5,2925,281.61,3
29836,mumbai,995000,bmw,3 series,4,diesel,46000,automatic,rwd,NaN,5,1995,170.00,14

In [ ]:
df.loc[df['model'] == '3 series', 'type'] = df.loc[df['model'] == '3 series', 'type'].fillna('sedan')

In [ ]:
df.loc[df['model'] == 's60', 'type'] = df.loc[df['model'] == 's60', 'type'].fillna('sedan')

In [ ]:
df.loc[df['model'] == 'xc90', 'type'] = df.loc[df['model'] == 'xc90', 'type'].fillna('suv')

In [ ]:
df.loc[df['model'] == 's 80', 'type'] = df.loc[df['model'] == 's 80', 'type'].fillna('sedan')

In [ ]:
df.loc[df['model'] == 's-class', 'type'] = df.loc[df['model'] == 's-class', 'type'].fillna('sedan')

In [ ]:
df.loc[df['model'] == 'huracan evo', 'type'] = df.loc[df['model'] == 'huracan evo', 'type'].fillna('coupe')

In [ ]:
df.loc[df['model'] == 'gtc4lusso', 'type'] = df.loc[df['model'] == 'gtc4lusso', 'type'].fillna('coupe')

In [ ]:
df.loc[df['model'] == '5 series', 'type'] = df.loc[df['model'] == '5 series', 'type'].fillna('sedan')

In [ ]:
df.isnull().sum()

region          0
price           0
manufacturer    0
model           0
cylinders       0
fuel            0
odometer        0
transmission    0
drive           0
type            0
seats           0
engine_cc       0
max_power       0
age             0
dtype: int64

In [ ]:
df[df['fuel'] == 'electric']

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
8042,new delhi,1850000,toyota,camry,0,electric,49500,automatic,fwd,sedan,5,0,157.7,6
17463,new delhi,2000000,toyota,camry,0,electric,60000,automatic,fwd,sedan,5,0,157.7,6
20079,new delhi,1865000,toyota,camry,0,electric,85000,automatic,fwd,sedan,5,0,157.7,5
20351,new delhi,1699000,toyota,camry,0,electric,64000,automatic,fwd,sedan,5,0,157.7,6
22290,bangalore,236000,mahindra,e2o,0,electric,52889,automatic,fwd,hatchback,4,0,25.5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34748,mumbai,1485000,tata,nexon ev prime,0,electric,12000,automatic,fwd,suv,5,0,127.0,6
35493,bangalore,1445000,tata,nexon ev prime,0,electric,28043,automatic,fwd,suv,5,0,127.0,5
35559,bangalore,1545000,tata,nexon ev prime,0,electric,5220,automatic,fwd,suv,5,0,127.0,4
36199,mumbai,2300000,mg,zs ev,0,electric,7500,automatic,fwd,suv,5,0,140.8,5
36253,mumbai,1575000,tata,nexon ev prime,0,electric,4000,automatic,fwd,suv,5,0,127.0,4

In [ ]:
df['cylinders'].unique().tolist()

[3, 4, 2, 6, 5, 0, 8, 1, 7, 10, 12]

In [ ]:
df[(df['model'] == 'camry') & (df['engine_cc'] == 0)]

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
8042,new delhi,1850000,toyota,camry,0,electric,49500,automatic,fwd,sedan,5,0,157.7,6
17463,new delhi,2000000,toyota,camry,0,electric,60000,automatic,fwd,sedan,5,0,157.7,6
20079,new delhi,1865000,toyota,camry,0,electric,85000,automatic,fwd,sedan,5,0,157.7,5
20351,new delhi,1699000,toyota,camry,0,electric,64000,automatic,fwd,sedan,5,0,157.7,6
22291,new delhi,1698999,toyota,camry,0,electric,96500,automatic,fwd,sedan,5,0,157.7,11
22296,new delhi,1650000,toyota,camry,0,electric,115000,automatic,fwd,sedan,5,0,157.7,10
22340,new delhi,1990000,toyota,camry,0,electric,185000,automatic,fwd,sedan,5,0,157.7,9
22363,mumbai,2299000,toyota,camry,0,electric,40418,automatic,fwd,sedan,5,0,157.7,9
22364,bangalore,1666000,toyota,camry,0,electric,79281,automatic,fwd,sedan,5,0,157.7,10
22382,pune,1900000,toyota,camry,0,electric,64712,automatic,fwd,sedan,5,0,157.7,11
22386,pune,1500000,toyota,camry,0,electric,74368,automatic,fwd,sedan,5,0,157.7,11
22405,bangalore,1400000,toyota,camry,0,electric,65011,automatic,fwd,sedan,5,0,157.7,11
22408,new delhi,1390000,toyota,camry,0,electric,108000,automatic,fwd,sedan,5,0,157.7,12

In [ ]:
df.loc[df['model'] == 'camry', 'cylinders'] = df.loc[df['model'] == 'camry', 'cylinders'].replace(0, 4)

In [ ]:
df.loc[df['model'] == 'camry', 'fuel'] = df.loc[df['model'] == 'camry', 'fuel'].replace('electric', 'petrol')

In [ ]:
df.loc[
    (df['engine_cc'] == 0) & (df['fuel'] == 'petrol'),
    'engine_cc'
] = np.nan

In [ ]:
df.isnull().sum()

region           0
price            0
manufacturer     0
model            0
cylinders        0
fuel             0
odometer         0
transmission     0
drive            0
type             0
seats            0
engine_cc       13
max_power        0
age              0
dtype: int64

In [ ]:
df['engine_cc'] = df.groupby(
    ['manufacturer', 'model', 'max_power']
)['engine_cc'].transform(
    lambda x: x.fillna(x.median() if not np.isnan(x.median()) else df['engine_cc'].median())
)

In [ ]:
df.isnull().sum()

region          0
price           0
manufacturer    0
model           0
cylinders       0
fuel            0
odometer        0
transmission    0
drive           0
type            0
seats           0
engine_cc       0
max_power       0
age             0
dtype: int64

In [ ]:
df['engine_cc'].value_counts()

engine_cc
1197.0    9539
1248.0    4594
998.0     4365
1498.0    3086
1497.0    3030
          ...
2579.0       1
3598.0       1
970.0        1
1490.0       1
1195.0       1
Name: count, Length: 185, dtype: int64

In [ ]:
df[(df['engine_cc'] == 0) & (df['fuel'] != 'electric')]

Empty DataFrame
Columns: [region, price, manufacturer, model, cylinders, fuel, odometer, transmission, drive, type, seats, engine_cc, max_power, age]
Index: []

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57763 entries, 0 to 57762
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   region        57763 non-null  object
 1   price         57763 non-null  int64
 2   manufacturer  57763 non-null  object
 3   model         57763 non-null  object
 4   cylinders     57763 non-null  int64
 5   fuel          57763 non-null  object
 6   odometer      57763 non-null  int64
 7   transmission  57763 non-null  object
 8   drive         57763 non-null  object
 9   type          57763 non-null  object
 10  seats         57763 non-null  int64
 11  engine_cc     57763 non-null  float64
 12  max_power     57763 non-null  float64
 13  age           57763 non-null  int64
dtypes: float64(2), int64(5), object(7)
memory usage: 6.2+ MB

In [ ]:
df.to_csv('cars_data_cleaned1_post_model_selection.csv', index = False)

In [ ]:
import joblib

In [ ]:
joblib.dump(df, 'cars_dataframe.pkl')

['cars_dataframe.pkl']

In [ ]:
import pandas as pd
import joblib

In [ ]:
df = pd.read_csv('cleaned_cars_merges.csv')

In [ ]:
joblib.dump(df, 'cleaned_cars_merges.pkl')

['cleaned_cars_merges.pkl']