In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('spinny_data.csv')

In [ ]:
df2 = pd.read_csv('cardekho_data_1.csv')

In [ ]:
df3 = pd.read_csv('cardekho_data2.csv')

In [ ]:
df1.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.0,petrol,20979,manual,fwd,hatchback,NaN,NaN,NaN,5
1,agra,745000,maruti suzuki,baleno,4.0,petrol,20176,manual,fwd,hatchback,NaN,NaN,NaN,3
2,agra,465000,hyundai,grand i10,3.0,cng,41448,manual,fwd,hatchback,NaN,NaN,NaN,7
3,agra,546000,maruti suzuki,celerio,3.0,petrol,8527,manual,fwd,hatchback,NaN,NaN,NaN,3
4,agra,428000,hyundai,santro,4.0,cng,102049,manual,fwd,hatchback,NaN,NaN,NaN,5

In [ ]:
df = pd.concat([df1, df2])

In [ ]:
6075 + 15216

21291

In [ ]:
df.shape

(21291, 14)

In [ ]:
df = pd.concat([df, df3])

In [ ]:
37814 + 21291

59105

In [ ]:
df.shape

(59105, 14)

In [ ]:
df.sample(20)

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
8395,NaN,350000.0,hyundai,i20,NaN,petrol,20000,manual,NaN,NaN,5.0,1197.0,80.00,11
9502,NaN,625000.0,maruti,dzire vxi,NaN,petrol,28000,manual,NaN,NaN,5.0,1197.0,88.50,3
5580,pune,247000.0,hyundai,i10,4.0,petrol,42110,manual,NaN,hatchback,NaN,NaN,NaN,13
3832,jaipur,449000.0,ford,figo,3.0,petrol,35160,manual,fwd,hatchback,NaN,NaN,NaN,6
1195,mumbai,695000.0,tata,tigor ev,NaN,electric,18500,automatic,fwd,sedan,5.0,NaN,40.23,7
24099,bangalore,300000.0,maruti,swift,4.0,petrol,75508,manual,NaN,hatchback,5.0,1298.0,88.20,19
4359,NaN,695000.0,maruti,swift,NaN,diesel,77600,automatic,NaN,NaN,5.0,1248.0,74.00,3
6352,NaN,185000.0,maruti,alto,NaN,petrol,76366,manual,NaN,NaN,5.0,796.0,46.30,14
35478,ghaziabad,235000.0,honda,accord,4.0,petrol,67889,manual,fwd,sedan,5.0,2354.0,177.60,17
29269,pune,850000.0,honda,city,4.0,petrol,75146,manual,fwd,sedan,5.0,1497.0,117.60,8
37348,pune,750000.0,hyundai,venue,4.0,petrol,9263,manual,fwd,suv,5.0,1197.0,81.86,5
2522,NaN,675000.0,toyota,innova,NaN,diesel,125000,manual,NaN,NaN,7.0,2494.0,102.00,10
2960,NaN,711000.0,maruti,ertiga,NaN,diesel,80000,manual,NaN,NaN,7.0,1248.0,88.80,8
2130,delhi,284000.0,honda,amaze,4.0,petrol,92911,manual,fwd,sedan,NaN,NaN,NaN,11
1926,nandurbar,620000.0,maruti,ertiga,4.0,diesel,60000,manual,fwd,muv,7.0,1248.0,88.76,12
13898,NaN,191000.0,maruti,swift dzire,NaN,petrol,110000,manual,NaN,NaN,5.0,1197.0,85.80,7
29185,mumbai,775000.0,honda,city,4.0,petrol,77000,automatic,fwd,sedan,5.0,1497.0,117.30,10
10802,new delhi,2200000.0,audi,q3,4.0,diesel,61000,automatic,awd,suv,5.0,1968.0,184.00,9
13690,NaN,260000.0,maruti,alto,NaN,petrol,40000,manual,NaN,NaN,5.0,998.0,67.05,6
107,NaN,1150000.0,mahindra,scorpio,NaN,diesel,46400,manual,NaN,NaN,7.0,2179.0,120.00,5

In [ ]:
df.to_csv('cars_data.csv', index = False)