In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Spinny_cars_data.csv')

In [ ]:
pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
df.sample(20)

,car_id,region,price,year,manufacturer,model,cylinder,fuel,odometer,transmission,drive,types,core_rating,supporting_rating,interior_rating,exterior_rating,wear_rating
1755,26762878,Noida,942000,2022,Volkswagen,Taigun,3.0,petrol,57441,manual,FWD,suv,9.8,9.6,9.3,8.9,8.7
1028,26211723,Bangalore,958000,2021,Volkswagen,Taigun,3.0,petrol,69966,automatic,FWD,suv,9.7,9.1,8.8,8.6,7.2
8890,26581631,Pune,362000,2015,Maruti Suzuki,Wagon R,3.0,cng,55754,manual,FWD,hatchback,9.6,9.3,8.5,7.9,7.1
2425,24473945,Chennai,1180000,2021,Hyundai,Creta,4.0,diesel,100118,automatic,FWD,suv,9.6,9.1,8.6,8.0,7.6
4475,24668173,Gurgaon,451000,2016,Volkswagen,Vento,4.0,petrol,83061,automatic,FWD,sedan,9.2,9.5,7.9,7.3,7.8
9028,25312052,Pune,967000,2022,Hyundai,Verna,4.0,petrol,23596,manual,FWD,sedan,9.9,9.7,9.7,9.2,9.1
4686,25220176,Gurgaon,1035108,2021,Jeep,Compass,4.0,petrol,74783,manual,FWD,suv,9.5,9.4,8.6,8.7,8.2
3249,23318660,Delhi,1503000,2023,Mahindra,XUV700,4.0,petrol,25235,manual,FWD,suv,9.8,9.8,9.5,8.5,8.8
6692,21544192,Hyderabad,768000,2022,Hyundai,Venue,3.0,petrol,23460,manual,FWD,suv,9.9,9.8,9.6,9.5,9.4
2694,26789511,Delhi,544000,2019,Maruti Suzuki,Swift,4.0,petrol,58014,automatic,FWD,hatchback,9.6,8.6,7.9,8.2,8.1
2439,25471796,Chennai,1432995,2022,Tata,Harrier,4.0,diesel,69992,manual,FWD,suv,9.5,9.1,8.5,8.4,8.5
2756,26171526,Delhi,290000,2017,Tata,Tiago,3.0,petrol,111774,manual,FWD,hatchback,8.6,8.7,8.2,7.5,7.2
7309,24710282,Lucknow,1299000,2024,Tata,Curvv,3.0,petrol,23498,manual,FWD,suv,9.9,9.8,9.4,9.4,9.1
4514,26611975,Noida,396000,2019,Honda,Amaze,NaN,cng,83918,manual,FWD,sedan,9.4,9.2,8.3,8.0,8.5
7071,22885783,Kolkata,321000,2013,Toyota,Etios,4.0,diesel,82422,manual,FWD,sedan,9.6,9.4,8.6,7.3,9.0
1633,26280355,Sonipat,392000,2018,Maruti Suzuki,Swift,4.0,petrol,95613,manual,FWD,hatchback,9.6,8.4,8.0,7.9,7.8
619,25360510,Bangalore,350000,2011,Hyundai,i20,4.0,petrol,70976,automatic,NaN,hatchback,9.7,9.5,8.5,8.3,8.2
3384,25724094,Delhi,365000,2015,Maruti Suzuki,Ciaz,4.0,petrol,52912,manual,FWD,sedan,8.9,9.2,8.6,7.5,7.4
4591,20842230,Delhi,562000,2017,Maruti Suzuki,Ciaz,4.0,petrol,49962,automatic,FWD,sedan,9.8,9.6,9.2,8.1,7.9
203,26609393,Bangalore,403000,2015,Hyundai,Xcent,4.0,petrol,65946,manual,FWD,sedan,9.4,8.8,8.1,8.1,8.2

In [ ]:
df.shape

(9153, 17)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9153 entries, 0 to 9152
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_id             9153 non-null   int64
 1   region             9153 non-null   object
 2   price              9153 non-null   int64
 3   year               9153 non-null   int64
 4   manufacturer       9153 non-null   object
 5   model              9153 non-null   object
 6   cylinder           8977 non-null   float64
 7   fuel               9153 non-null   object
 8   odometer           9153 non-null   int64
 9   transmission       9153 non-null   object
 10  drive              8854 non-null   object
 11  types              9153 non-null   object
 12  core_rating        9153 non-null   float64
 13  supporting_rating  9153 non-null   float64
 14  interior_rating    9140 non-null   float64
 15  exterior_rating    9140 non-null   float64
 16  wear_rating        9153 non-null   float64
dtypes: float64(6), int64(4), object(7)
memory usage: 1.2+ MB

In [ ]:
# we have to drop cols like car_id
# we have to make a single column named condition with the help of core_rating, supporting_rating, interior_rating, exterior_rating, wear_rating
# may be some columns need to renamed like cylinder has to renamed as cylinders and types as type

In [ ]:
# we have to change the type of the cylinder col to int

In [ ]:
df.drop(columns = ['car_id'], inplace = True)

In [ ]:
df.rename(columns = {'cylinder': 'cylinders', 'types': 'type'}, inplace = True)

In [ ]:
df.head()

,region,price,year,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,core_rating,supporting_rating,interior_rating,exterior_rating,wear_rating
0,Agra,512000,2021,Tata,Tiago,3.0,petrol,20979,manual,FWD,hatchback,9.9,9.4,9.3,8.7,9.2
1,Agra,745000,2023,Maruti Suzuki,Baleno,4.0,petrol,20176,manual,FWD,hatchback,9.9,9.9,9.5,9.0,9.5
2,Agra,465000,2019,Hyundai,Grand i10,3.0,cng,41448,manual,FWD,hatchback,9.5,9.7,7.8,8.0,7.2
3,Agra,546000,2023,Maruti Suzuki,Celerio,3.0,petrol,8527,manual,FWD,hatchback,9.9,9.9,9.5,9.4,9.5
4,Agra,428000,2021,Hyundai,Santro,4.0,cng,102049,manual,FWD,hatchback,9.2,8.8,7.9,8.1,6.7

In [ ]:
# need to change new i20 to i20
# values of region, manufacturer, model, drive has to be in lower case

In [ ]:
df['region'] = df['region'].str.lower()
df['manufacturer'] = df['manufacturer'].str.lower()
df['model'] = df['model'].str.lower()
df['drive'] = df['drive'].str.lower()
df['fuel'] = df['fuel'].str.lower()
df['transmission'] = df['transmission'].str.lower()
df['type'] = df['type'].str.lower()

In [ ]:
df.drop(columns = (['core_rating', 'supporting_rating', 'interior_rating', 'exterior_rating', 'wear_rating']), inplace = True)

In [ ]:
df.head()

,region,price,year,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type
0,agra,512000,2021,tata,tiago,3.00,petrol,20979,manual,fwd,hatchback
1,agra,745000,2023,maruti suzuki,baleno,4.00,petrol,20176,manual,fwd,hatchback
2,agra,465000,2019,hyundai,grand i10,3.00,cng,41448,manual,fwd,hatchback
3,agra,546000,2023,maruti suzuki,celerio,3.00,petrol,8527,manual,fwd,hatchback
4,agra,428000,2021,hyundai,santro,4.00,cng,102049,manual,fwd,hatchback

In [ ]:
df.duplicated().sum()

np.int64(3078)

In [ ]:
9153 - 3078

6075

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(6075, 11)

In [ ]:
df.columns

Index(['region', 'price', 'year', 'manufacturer', 'model', 'cylinders', 'fuel',
       'odometer', 'transmission', 'drive', 'type'],
      dtype='object')

In [ ]:
df['seats'] = np.nan

In [ ]:
df['engine_cc'] = np.nan

In [ ]:
df['max_power'] = np.nan

In [ ]:
import datetime

In [ ]:
df['age'] = datetime.datetime.now().year - df['year']

In [ ]:
df.drop(columns = ['year'], inplace = True)

In [ ]:
df.head()

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
0,agra,512000,tata,tiago,3.00,petrol,20979,manual,fwd,hatchback,NaN,NaN,NaN,5
1,agra,745000,maruti suzuki,baleno,4.00,petrol,20176,manual,fwd,hatchback,NaN,NaN,NaN,3
2,agra,465000,hyundai,grand i10,3.00,cng,41448,manual,fwd,hatchback,NaN,NaN,NaN,7
3,agra,546000,maruti suzuki,celerio,3.00,petrol,8527,manual,fwd,hatchback,NaN,NaN,NaN,3
4,agra,428000,hyundai,santro,4.00,cng,102049,manual,fwd,hatchback,NaN,NaN,NaN,5

In [ ]:
df.shape

(6075, 15)

In [ ]:
df1 = pd.read_csv('cardekho_data_1.csv')

In [ ]:
df1.shape

(15216, 14)

In [ ]:
df2 = pd.read_csv('cardekho_data2.csv')

In [ ]:
df2.shape

(37814, 14)

In [ ]:
df1.columns

Index(['manufacturer', 'model', 'age', 'odometer', 'fuel', 'transmission',
       'engine_cc', 'max_power', 'seats', 'price', 'region', 'type',
       'cylinders', 'drive'],
      dtype='object')

In [ ]:
df2.columns

Index(['type', 'transmission', 'fuel', 'price', 'engine_cc', 'max_power',
       'cylinders', 'seats', 'model', 'manufacturer', 'odometer', 'region',
       'drive', 'age'],
      dtype='object')

In [ ]:
df.columns

Index(['region', 'price', 'manufacturer', 'model', 'cylinders', 'fuel',
       'odometer', 'transmission', 'drive', 'type', 'seats', 'engine_cc',
       'max_power', 'age'],
      dtype='object')

In [ ]:
df.drop(columns = ['tranmission'], inplace = True)

KeyError: "['tranmission'] not found in axis"

In [ ]:
df.shape

(6075, 14)

In [ ]:
df1.sample(10)

,manufacturer,model,age,odometer,fuel,transmission,engine_cc,max_power,seats,price,region,type,cylinders,drive
9547,mercedes-benz,c-class,3,8000,petrol,automatic,1991,181.04,5,3650000,NaN,NaN,NaN,NaN
14144,honda,city,22,70000,petrol,manual,1493,100.00,5,70000,NaN,NaN,NaN,NaN
3445,volkswagen,vento,8,83469,diesel,manual,1498,103.20,5,485000,NaN,NaN,NaN,NaN
9435,maruti,swift,7,42000,diesel,manual,1248,74.00,5,365000,NaN,NaN,NaN,NaN
9405,maruti,swift dzire,6,57429,petrol,manual,1197,85.80,5,450000,NaN,NaN,NaN,NaN
7623,honda,amaze,8,39500,diesel,manual,1498,98.60,5,320000,NaN,NaN,NaN,NaN
10079,bmw,x4,2,7500,diesel,automatic,1995,190.00,5,5810000,NaN,NaN,NaN,NaN
9404,volkswagen,vento,7,59484,petrol,manual,1598,103.20,5,465000,NaN,NaN,NaN,NaN
6343,hyundai,grand,5,30000,petrol,manual,1197,82.00,5,420000,NaN,NaN,NaN,NaN
7125,datsun,go,3,9605,petrol,manual,1198,67.00,7,530000,NaN,NaN,NaN,NaN

In [ ]:
df.sample(10)

,region,price,manufacturer,model,cylinders,fuel,odometer,transmission,drive,type,seats,engine_cc,max_power,age
8604,pune,504000,hyundai,xcent,4.00,petrol,70469,manual,fwd,sedan,NaN,NaN,NaN,7
6914,kanpur,506000,renault,kiger,3.00,petrol,26683,manual,fwd,suv,NaN,NaN,NaN,5
8291,pune,354000,maruti suzuki,wagon r,3.00,petrol,33129,manual,fwd,hatchback,NaN,NaN,NaN,10
622,bangalore,770000,honda,jazz,4.00,petrol,26647,automatic,fwd,hatchback,NaN,NaN,NaN,5
6839,jaipur,725000,honda,city,4.00,petrol,46723,automatic,fwd,sedan,NaN,NaN,NaN,8
7605,mumbai,252000,maruti suzuki,wagon r,3.00,petrol,54819,manual,fwd,hatchback,NaN,NaN,NaN,12
1019,bangalore,323000,honda,brio,4.00,petrol,70424,manual,fwd,hatchback,NaN,NaN,NaN,12
8975,pune,1072523,volkswagen,taigun,3.00,petrol,17249,automatic,fwd,suv,NaN,NaN,NaN,4
2104,noida,305000,tata,tiago,3.00,petrol,93733,automatic,fwd,hatchback,NaN,NaN,NaN,9
8310,pune,1691653,kia,seltos,4.00,petrol,17696,automatic,fwd,suv,NaN,NaN,NaN,3

In [ ]:
df.to_csv('spinny_data.csv', index = False)